export const environment = {
  production: false,
  apiUrl: 'http://localhost:8080',
  endpoints: {
    register: '/register',
    login: '/login',
    getProfileById: '/user/profile/',
    getMyProfile: '/user/my-profile',
    getAdminStats: '/admin/users/statistics',
    getQuizzCompletionStats: '/admin/quizzes/completion-stats',
    getTechnologyPopularity: '/admin/technologies/popular',
    getRecentActivities: '/admin/users/recent-activities',
    getUserActivity: '/admin/users/activity',
    getAllUsersAdmin: '/admin/users',
    deleteUserAdmin: '/admin/users/',
    updateUserAdmin: '/admin/users/',
    getUserByIdAdmin: '/admin/users/',
    getRankingByUserIdAdmin: '/admin/rankings/user/',
    createUserAdmin: '/admin/users',
    getAllTechnologiesAdmin: '/admin/technologies',
    createQuizzAdmin: '/admin/quizzes',
    addQuestionAdmin: '/admin/questions',
    deleteQuestionAdmin: '/admin/questions/',
    updateQuestionAdmin: '/admin/questions',
    getAllQuizzesAdmin: '/admin/quizzes',
    getQuizzByIdAdmin: '/admin/quizzes/',
    getQuestionsByQuizIdAdmin: '/admin/questions/quizz/',
    deleteQuizzAdmin: '/admin/quizzes/',
    updateQuizzAdmin: '/admin/quizzes',
  },
};
